### ISSUE TITLE
Document SQL API

### ISSUE THREAD

**Issue by cbrake** [genjidb/docs#3]
It appears there are quite a few new SQL features being added and things that are not documented yet. One example is:

```sql
CREATE TABLE IF NOT EXISTS users;
```
What is the best way to document SQL for this project? Does anyone have examples of something we should follow?

Some examples:

* https://sqlite.org/lang.html
* https://dev.mysql.com/doc/refman/8.0/en/sql-statements.html

Posgresql SQL doc seems to be in a PDF:

![image](https://user-images.githubusercontent.com/402813/96337512-b4695a80-1055-11eb-968f-823330b354f5.png)

**Comment by asdine** [comment]
I was thinking of having two sections:

- One that acts like a tutorial for each statement. This is what we currently have for most statements. It is not supposed to be exhaustive but rather explain how the statement works in general. https://genji.dev/docs/genji-sql/
- One `API Reference` section that would describe the statement clause by clause. Something like this https://dev.mysql.com/doc/refman/8.0/en/create-index.html, though it wouldn't have to be that detailed.

I'm open to any suggestions though

**Comment by cbrake** [comment]
genji sql: 

* [x] ALTER
* [x] BEGIN
* [x] COMMIT
* [x] SELECT
* [x] DELETE
* [x] UPDATE
* [x] INSERT
* [x] CREATE
* [x] DROP
* [x] EXPLAIN
* [x] REINDEX
* [x] ROLLBACK
* [ ] GROUP BY

From https://github.com/genjidb/genji/pull/323:

-- valid
SELECT COUNT(id), country FROM users GROUP BY country;
SELECT age % 10 FROM users GROUP BY age % 10;

-- invalid
SELECT COUNT(id), age FROM users GROUP BY country;
field "age" must appear in the GROUP BY clause or be used in an aggregate function

SELECT age % 10 FROM users GROUP BY age;
field "age % 10" must appear in the GROUP BY clause or be used in an aggregate function

**Comment by asdine** [comment]
The [new section](https://genji.dev/docs/reference/) has been added to the docs (almost 1 year later :D), it is not complete but new updates will follow.
Closing this issue, thanks @cbrake !
